### ISSUE TITLE
1.20.4 lost connection issuse 

### ISSUE THREAD

**Issue by MAG10d** [EuSouVoce/FartherViewDistance_1.20.1#2] opened 2024-05-28 02:35 UTC
[10:10:42] [Server thread/INFO]: luckmoiJay lost connection: Internal Exception: java.lang.NoSuchMethodError: 'void xuan.cat.fartherviewdistance.api.branch.packet.PacketUnloadChunkEvent.<init>(org.bukkit.entity.Player, net.minecraft.world.level.ChunkCoordIntPair)'

Full log here: https://mclo.gs/DCW02VC

**Comment by MrDzharik** [comment] 2024-06-02 16:50
I am getting the same error, hopefully the author will notice and fix it soon

**Comment by DadmanAAA** [comment] 2024-06-24 08:28
Такая же ошибка ☻

**Comment by EuSouVoce** [comment] 2024-07-07 15:57
Fixed in v9.9.2

**Closed by EuSouVoce** 2024-07-07 15:57 UTC

**Comment by EuSouVoce** [comment] 2024-07-07 15:58
Please update your server to the stable 1.20.6 as soon as possible since the way that the packets are read in 1.20.4 lead to those disconnects, I've made a hotfix but the issue is with the version.
